"""THREADLINE — NYC official buildings for the scan map (seed MAN).

Replaces the scan's blobby buildings with the NYC Department of City Planning 3D model (2014), placed in the
scan's world frame through tools/scan/nyc_affine.json (found by registering the two height maps).

Geometry (see rebuild_walls): a building is its ROOF surfaces from the DCP model; every wall is regenerated by
hanging a vertical face from each roof boundary edge down to whatever is just outside that edge (a lower roof of
the same building, a neighbour's roof, or the ground). The DCP facade surfaces are only used for buildings that
have no roof. This makes every building closed and watertight by construction: no wall sheets sticking up past a
setback, no walls floating above a roof, no doubled / z-fighting walls, no party walls buried inside a
neighbour. Towers that the 2014 model does not have (newer buildings the scan shows) are added as extruded
prisms from the scan's own height map (scan_only_buildings), so no piece of the raw scan stands as a building.

Inputs : build/nyc_raw.pkl (tools/scan/nyc_extract.py), build/scan.json + scan.bin + scan_flat.npz
         (tools/scan/build_scan.py: frame, land mask, flattened scan for the colour bake), the scan texture.
Outputs: build/nyc.bin / nyc.json  buildings (flat triangles + per-vertex atlas UVs, per-building facade
                                   style/colour) + oriented box colliders fitted per building in its own orientation
         build/nyc_atlas.webp      the scan's colour baked per building (tools/scan/bake_nyc.py)
         build/nyc_mask.npz        0.5 m footprint id raster in the scan frame (build_scan.py uses it to cut
                                   the scan's buildings out and keep ground, trees, piers, the FDR)
         build/nyc_ground.jpg      street / sidewalk / park ground texture from the DCP linework
All paths honour TL_BUILD_DIR (via build_scan.OUT).
Usage  : python tools/scan/build_nyc.py
"""
import json, os, pickle, sys, time
import numpy as np
import cv2
from PIL import Image
from scipy import ndimage as nd
import open3d as o3d

sys.path.insert(0, os.path.dirname(__file__))
import build_scan as BS
import bake_nyc

ROOT = BS.ROOT
OUT = BS.OUT
FT = 0.3048
RC = 0.5            # footprint raster cell (m)
CC = 1.0            # per-building collision cell (m)
TILE = 160.0
WALL_BASE = -0.3    # walls that reach the street go this far under the ground plane (no light leak at the base)
EDGE_STEP = 0.5     # roof-edge probe spacing (m)
PROBE_OUT = 0.08    # probe distance outside a roof edge (m)
MIN_WALL = 0.25     # smaller height steps between a roof edge and what is outside it get no wall


def log(*a): print('[nyc]', *a, flush=True)


def tri_normals(T):
    n = np.cross(T[:, 1] - T[:, 0], T[:, 2] - T[:, 0]); l = np.linalg.norm(n, axis=1)
    return n / np.maximum(l, 1e-12)[:, None], 0.5 * l


def clean_tris(T, min_area=2e-3, min_alt=0.02):
    """drop degenerate / needle triangles (zero area, or thinner than 2 cm across their longest edge)"""
    if not len(T): return T
    _, a = tri_normals(T)
    L = np.stack([np.linalg.norm(T[:, 1] - T[:, 0], axis=1), np.linalg.norm(T[:, 2] - T[:, 1], axis=1),
                  np.linalg.norm(T[:, 0] - T[:, 2], axis=1)], 1).max(1)
    return T[(a > min_area) & (2 * a / np.maximum(L, 1e-9) > min_alt)]


def boundary_edges(T):
    """edges used by exactly one triangle of this surface (vertices welded at 5 mm) ->
    (a, b, third vertex of the owning triangle, owning triangle index)"""
    V = T.reshape(-1, 3)
    _, inv = np.unique(np.round(V * 200).astype(np.int64), axis=0, return_inverse=True)
    inv = inv.reshape(-1); I = inv.reshape(-1, 3); nv = int(inv.max()) + 1
    Vu = np.zeros((nv, 3)); Vu[inv] = V
    E = np.concatenate([I[:, [0, 1]], I[:, [1, 2]], I[:, [2, 0]]])
    third = np.concatenate([I[:, 2], I[:, 0], I[:, 1]])
    owner = np.tile(np.arange(len(I)), 3)
    s = np.sort(E, 1); key = s[:, 0].astype(np.int64) * nv + s[:, 1]
    _, first, cnt = np.unique(key, return_index=True, return_counts=True)
    b = first[cnt == 1]
    b = b[E[b, 0] != E[b, 1]]
    return Vu[E[b, 0]], Vu[E[b, 1]], Vu[third[b]], owner[b]


class TopProbe:
    """highest roof surface under a set of XZ points (all buildings, ground-relative heights)"""
    def __init__(self, tris):
        self.scene = o3d.t.geometry.RaycastingScene()
        V = tris.reshape(-1, 3).astype(np.float32)
        self.scene.add_triangles(o3d.core.Tensor(V), o3d.core.Tensor(np.arange(len(V), dtype=np.uint32).reshape(-1, 3)))

    def height(self, x, z, top=3000.0):
        n = len(x); out = np.full(n, -np.inf)
        for s in range(0, n, 4_000_000):
            m = min(n, s + 4_000_000) - s
            r = np.zeros((m, 6), np.float32); r[:, 0] = x[s:s + m]; r[:, 1] = top; r[:, 2] = z[s:s + m]; r[:, 4] = -1
            th = self.scene.cast_rays(o3d.core.Tensor(r))['t_hit'].numpy()
            out[s:s + m] = np.where(np.isfinite(th), top - th, -np.inf)
        return out


def rebuild_walls(blds):
    """Walls hang from roof edges. For every boundary edge of every roof surface (flat enough to be a roof), probe
    the highest surface just outside the edge every EDGE_STEP metres; where it is lower than the edge a vertical
    face is extruded from the edge down to it (to WALL_BASE for the street). The bottom of each piece is the lowest
    probe of it and its neighbours, so no slit opens where a neighbour's roof steps down between two probes.
    Sets b['S'] (list of chart surfaces), b['Sk'] ('roof' | 'wall' per surface) and b['T']."""
    t0 = time.time()
    allR = np.concatenate([np.concatenate(b['roofs']) for b in blds if b['roofs']])
    probe = TopProbe(allR)
    # roofs entirely under a higher surface (the DCP model stacks some) are invisible: drop them
    # (a triangle is hidden only if its centre, its corners and its edge midpoints - all pulled 3 % inwards - are)
    dropped = 0
    for b in blds:
        keep = []
        for R in b['roofs']:
            c = R.mean(1)
            pts = [c] + [c + (R[:, k] - c) * 0.97 for k in range(3)] + [c + ((R[:, k] + R[:, (k + 1) % 3]) / 2 - c) * 0.97 for k in range(3)]
            P = np.concatenate(pts)
            h = probe.height(P[:, 0], P[:, 2]).reshape(len(pts), -1)
            hidden = (h > P[:, 1].reshape(len(pts), -1) + 0.3).all(0)
            dropped += int(hidden.sum())
            if (~hidden).any(): keep.append(R[~hidden])
        b['roofs'] = keep
    probe = TopProbe(np.concatenate([np.concatenate(b['roofs']) for b in blds if b['roofs']]))
    # boundary edges of all roof surfaces
    ea, eb, ec, eo = [], [], [], []
    for bi, b in enumerate(blds):
        for R in b['roofs']:
            nr, _ = tri_normals(R)
            a, bb, c, own = boundary_edges(R)
            ok = np.abs(nr[own, 1]) > 0.3
            ea.append(a[ok]); eb.append(bb[ok]); ec.append(c[ok]); eo.append(np.full(ok.sum(), bi))
    ea, eb, ec, eo = map(np.concatenate, (ea, eb, ec, eo))
    d = (eb - ea)[:, [0, 2]]; L = np.linalg.norm(d, axis=1)
    ok = L > 0.05
    ea, eb, ec, eo, d, L = ea[ok], eb[ok], ec[ok], eo[ok], d[ok], L[ok]
    nrm = np.stack([-d[:, 1], d[:, 0]], 1) / L[:, None]
    flip = ((ec - ea)[:, [0, 2]] * nrm).sum(1) > 0
    nrm[flip] *= -1                                          # outward: away from the owning triangle
    K = np.maximum(1, np.ceil(L / EDGE_STEP)).astype(int)
    ei = np.repeat(np.arange(len(L)), K)
    start = np.concatenate([[0], np.cumsum(K)[:-1]])
    kk = np.arange(len(ei)) - start[ei]
    t = (kk + 0.5) / K[ei]
    px = ea[ei, 0] + (eb[ei, 0] - ea[ei, 0]) * t + nrm[ei, 0] * PROBE_OUT
    pz = ea[ei, 2] + (eb[ei, 2] - ea[ei, 2]) * t + nrm[ei, 1] * PROBE_OUT
    hout = probe.height(px, pz)
    ye = ea[ei, 1] + (eb[ei, 1] - ea[ei, 1]) * t
    bot = np.where(np.isfinite(hout), hout, WALL_BASE)
    bot = np.where(bot < 0.15, WALL_BASE, bot)               # the street (and kerb-high bits) -> under the ground
    # neighbour-min along each edge (a step in the outside height between two probes must not leave a slit)
    prev = np.where(kk > 0, np.roll(bot, 1), bot); nxt = np.where(kk < K[ei] - 1, np.roll(bot, -1), bot)
    bmin = np.minimum(bot, np.minimum(prev, nxt))
    need = bot < ye - MIN_WALL
    walls = [[] for _ in blds]
    for e in range(len(L)):
        s0, n = start[e], K[e]
        nd_, bm = need[s0:s0 + n], bmin[s0:s0 + n]
        if not nd_.any(): continue
        k = 0
        while k < n:
            if not nd_[k]: k += 1; continue
            k1 = k; lo = bm[k]
            while k1 + 1 < n and nd_[k1 + 1] and abs(bm[k1 + 1] - bm[k]) < 0.3: k1 += 1; lo = min(lo, bm[k1])
            t0_, t1_ = k / n, (k1 + 1) / n
            A = ea[e] + (eb[e] - ea[e]) * t0_; B = ea[e] + (eb[e] - ea[e]) * t1_
            yb = lo - 0.05 if lo > 0 else WALL_BASE
            a0, b0, a1, b1 = np.array([A[0], yb, A[2]]), np.array([B[0], yb, B[2]]), A.copy(), B.copy()
            q1, q2 = np.array([a0, b0, b1]), np.array([a0, b1, a1])
            fn = np.cross(b0 - a0, a1 - a0)
            if fn[0] * nrm[e, 0] + fn[2] * nrm[e, 1] < 0: q1, q2 = q1[[0, 2, 1]], q2[[0, 2, 1]]
            walls[eo[e]].append((np.stack([q1, q2]), nrm[e], float(nrm[e, 0] * A[0] + nrm[e, 1] * A[2])))
            k = k1 + 1
    nw = 0
    for b, W in zip(blds, walls):
        S, Sk = [R for R in b['roofs']], ['roof'] * len(b['roofs'])
        for grp in group_planar(W):
            S.append(np.concatenate(grp)); Sk.append('wall'); nw += len(grp)
        if b.get('keep_facades'):
            for F in b['facades']: S.append(F); Sk.append('wall')
        b['S'], b['Sk'] = S, Sk
        b['T'] = np.concatenate(S) if S else np.zeros((0, 3, 3))
    log('walls from roof edges: %d edges, %d probes, %d wall quads, %d hidden roof tris dropped, %.1fs'
        % (len(L), len(ei), nw, dropped, time.time() - t0))


def group_planar(W, ang=np.radians(2.0), dist=0.3, gap=2.0):
    """wall quads [(tris(2,3,3), outward nrm xz, offset)] -> groups on one plane and connected along it (one atlas
    chart each, so a facade's texture runs continuously across the pieces it was cut into)"""
    groups = []
    for q, n, o in W:
        for g in groups:
            if abs(np.arctan2(n[1], n[0]) - np.arctan2(g['n'][1], g['n'][0])) % (2 * np.pi) < ang or \
               abs(np.arctan2(n[1], n[0]) - np.arctan2(g['n'][1], g['n'][0])) % (2 * np.pi) > 2 * np.pi - ang:
                if abs(o - g['o']) < dist:
                    g['q'].append(q); break
        else: groups.append({'n': n, 'o': o, 'q': [q]})
    out = []
    for g in groups:
        # split along the plane's horizontal axis where pieces are more than `gap` apart
        u = np.array([-g['n'][1], g['n'][0]])
        span = [((q[..., [0, 2]] @ u).min(), (q[..., [0, 2]] @ u).max(), q) for q in g['q']]
        span.sort(key=lambda s: s[0])
        cur, hi = [], -np.inf
        for lo_, hi_, q in span:
            if cur and lo_ > hi + gap: out.append(cur); cur = []
            cur.append(q); hi = max(hi, hi_) if cur[:-1] else hi_
        if cur: out.append(cur)
    return out


def building_colliders(T, rng, hollow=False, inside=None):
    """(n,3,3) building triangles (ground-relative Y) -> oriented boxes (x, top, z, hx, hz, yaw): a 1 m
    top-surface height map in the building's own min-area-rect frame, greedily merged"""
    boxes = []
    e1, e2 = T[:, 1] - T[:, 0], T[:, 2] - T[:, 0]
    ar = 0.5 * np.linalg.norm(np.cross(e1, e2), axis=1)
    n = np.clip(np.ceil(ar / 0.25), 3, 4000).astype(int)
    ii = np.repeat(np.arange(len(T)), n)
    a = rng.random((len(ii), 1)); c_ = rng.random((len(ii), 1)); m = (a + c_) > 1; a[m] = 1 - a[m]; c_[m] = 1 - c_[m]
    p = T[ii, 0] + e1[ii] * a + e2[ii] * c_
    pts = np.concatenate([p, T.reshape(-1, 3)])
    rect = cv2.minAreaRect(pts[:, [0, 2]].astype(np.float32))
    al = np.radians(rect[2]); ca, sa = np.cos(al), np.sin(al)
    cx, cz = rect[0]
    lx = (pts[:, 0] - cx) * ca + (pts[:, 2] - cz) * sa
    lz = -(pts[:, 0] - cx) * sa + (pts[:, 2] - cz) * ca
    i0, k0 = np.floor(lx.min() / CC), np.floor(lz.min() / CC)
    gi = (np.floor(lx / CC) - i0).astype(int); gk = (np.floor(lz / CC) - k0).astype(int)
    HG = np.zeros((gk.max() + 1, gi.max() + 1))
    # solid where the ROOF really is: count surface samples per 1 m cell (wall triangles only touch their edge cells) —
    # the old 3x3 median + closing grew every box up to ~2 m past the visible walls ("invisible walls")
    nr = np.cross(e1, e2); roofs = np.abs(nr[:, 1]) > 0.5 * np.linalg.norm(nr, axis=1)
    # every roof AND wall triangle rasterised by exact coverage at half-cell resolution, highest wins (walls raise the
    # cells they stand on to their top edge: parapets / taller bays above a lower roof). A 1 m cell is solid when at
    # least half of it is covered — the previous sample-count / any-touch rules were 1-2 m off in either direction.
    F = 2
    HRi = np.zeros((HG.shape[0] * F, HG.shape[1] * F), np.int32)
    lxt = ((T[..., 0] - cx) * ca + (T[..., 2] - cz) * sa) / CC - i0
    lzt = (-(T[..., 0] - cx) * sa + (T[..., 2] - cz) * ca) / CC - k0
    ymax = T[..., 1].max(1)
    for k in np.argsort(ymax):
        poly = np.round(np.stack([lxt[k], lzt[k]], 1) * F * 16).astype(np.int32)
        v = int(round(ymax[k] * 10))
        if roofs[k]:
            cv2.fillPoly(HRi, [poly], v, shift=4)
        else:
            cv2.polylines(HRi, [poly], True, v, 1, shift=4)
    blk = HRi.reshape(HG.shape[0], F, HG.shape[1], F).transpose(0, 2, 1, 3).reshape(HG.shape[0], HG.shape[1], F * F)
    HR = np.where((blk > 0).sum(-1) >= 2, blk.max(-1), 0).astype(np.float64) / 10.0
    HA = np.zeros(HG.shape); np.maximum.at(HA, (gk, gi), pts[:, 1])      # everything (walls included), unfiltered
    if (HR > 0).sum() >= 0.5 * (HA > 0).sum():
        HG = nd.grey_closing(HR, size=2)
    else:                                          # facade-only / roofless data: keep the generous fit so it stays solid
        HG = np.maximum(HA, nd.median_filter(HA, 3) * (HA > 0)); HG = nd.grey_closing(HG, size=2)
    if inside is not None and not hollow:
        # buildings are solid: every cell whose centre lies in the footprint is filled (walls above roofless / holed parts of
        # the source data used to leave walk-through interiors), at the nearest roof height; roof-only cells (overhangs) stay
        gw_, gh_ = np.meshgrid((i0 + np.arange(HG.shape[1]) + 0.5) * CC, (k0 + np.arange(HG.shape[0]) + 0.5) * CC)
        wxg = cx + gw_ * ca - gh_ * sa; wzg = cz + gw_ * sa + gh_ * ca
        M = nd.binary_erosion(inside(wxg, wzg), iterations=1)      # interior only: the drawn walls/roof set the outline
        if (HG > 0).any():
            fill = nd.distance_transform_edt(HG <= 0, return_distances=False, return_indices=True)
            HG = np.where(M & (HG <= 0), HG[tuple(fill)], HG)
        else:
            HG = np.where(M, float(T[..., 1].max()), 0.0)
    q = np.round(HG / 0.5) * 0.5
    q[q < 2.0] = 0
    lowq = np.full(q.shape, -1.0)
    if hollow:                                # bridges: solid only between each cell's lowest and highest surface
        LG = np.full(HG.shape, 1e9); np.minimum.at(LG, (gk, gi), pts[:, 1]); LG[LG > 1e8] = -1
        lowq = np.where(q > 0, np.round(np.maximum(LG, -1)), -1.0)
        lowq = np.minimum(lowq, q - 1.0)
    key = q * 10000 + lowq
    used = np.zeros(q.shape, bool)
    for k in range(q.shape[0]):
        j = 0
        while j < q.shape[1]:
            if q[k, j] <= 0 or used[k, j]: j += 1; continue
            hv = q[k, j]; kv = key[k, j]; j1 = j
            while j1 + 1 < q.shape[1] and key[k, j1 + 1] == kv and not used[k, j1 + 1]: j1 += 1
            k1 = k
            while k1 + 1 < q.shape[0] and np.all(key[k1 + 1, j:j1 + 1] == kv) and not used[k1 + 1, j:j1 + 1].any(): k1 += 1
            used[k:k1 + 1, j:j1 + 1] = True
            blx, blz = (i0 + (j + j1 + 1) / 2) * CC, (k0 + (k + k1 + 1) / 2) * CC
            # local (along the rect axes) -> world; game yaw convention: world = (lx*c + lz*s, -lx*s + lz*c), yaw = -al
            wx, wz = cx + blx * ca - blz * sa, cz + blx * sa + blz * ca
            box = (wx, hv, wz, (j1 - j + 1) * CC / 2, (k1 - k + 1) * CC / 2, -al)
            boxes.append(box + (lowq[k, j],) if hollow else box)
            j = j1 + 1
    return boxes


class Ctx:
    """inputs shared by the stages: scan frame + land mask, DCP surfaces in the scan's world frame"""
    def __init__(self):
        self.meta = json.load(open(os.path.join(OUT, 'scan.json')))
        self.aff = np.array(json.load(open(os.path.join(os.path.dirname(__file__), 'nyc_affine.json')))['affine'])
        rawall = pickle.load(open(os.path.join(OUT, 'nyc_raw.pkl'), 'rb'))
        self.raw, self.lines = rawall['mesh'], rawall['lines']
        m = self.meta
        scanbin = open(os.path.join(OUT, 'scan.bin'), 'rb').read()
        self.land = np.frombuffer(scanbin, np.uint8, m['nx'] * m['nz'], m['land']).reshape(m['nz'], m['nx'])
        self.X0, self.Z0 = m['min'][0], m['min'][2]
        self.X1, self.Z1 = m['max'][0], m['max'][2]
        self.GW, self.GH = int(np.ceil((self.X1 - self.X0) / RC)), int(np.ceil((self.Z1 - self.Z0) / RC))

    def tf(self, V):                # (n,3) feet EPSG:2263 -> (n,3) scan world (X, elevation m, Z)
        a = self.aff
        E, N, U = V[:, 0] * FT, V[:, 1] * FT, V[:, 2] * FT
        return np.stack([a[0, 0] * E + a[0, 1] * N + a[0, 2], U, a[1, 0] * E + a[1, 1] * N + a[1, 2]], 1)

    def px(self, T): return np.stack([(T[..., 0] - self.X0) / RC, (T[..., 2] - self.Z0) / RC], -1)


def load_buildings(C):
    """DCP surfaces -> per-building roofs (+ source facades), ground-relative; footprint id raster"""
    t0 = time.time()
    X0, Z0, X1, Z1, GW, GH = C.X0, C.Z0, C.X1, C.Z1, C.GW, C.GH
    surf = {}
    for key in ('foot', 'roof', 'facade'):
        L = []
        for _, V, F in C.raw[key]:
            T = C.tf(V)[F]
            c = T.reshape(-1, 3).mean(0)
            if X0 - 30 < c[0] < X1 + 30 and Z0 - 30 < c[2] < Z1 + 30: L.append(T)
        surf[key] = L
        log(key, len(L), 'surfaces in the scan area')
    # ------------------------------------------------------------ footprint id raster (building = footprint surface)
    ids = np.zeros((GH, GW), np.int32)
    foot_y = {}
    nb = 0
    for T in surf['foot']:
        nb += 1; foot_y[nb] = float(np.median(T[..., 1]))
        for tri in C.px(T): cv2.fillPoly(ids, [np.round(tri * 8).astype(np.int32)], nb, shift=3)
    # roofs without a footprint become their own building
    roof_id = []
    for T in surf['roof']:
        q = C.px(T).reshape(-1, 2).mean(0).astype(int)
        i = ids[np.clip(q[1], 0, GH - 1), np.clip(q[0], 0, GW - 1)] if 0 <= q[0] < GW and 0 <= q[1] < GH else 0
        if i == 0:
            nb += 1; i = nb
            for tri in C.px(T): cv2.fillPoly(ids, [np.round(tri * 8).astype(np.int32)], i, shift=3)
        roof_id.append(i)
    near_d, near_i = nd.distance_transform_edt(ids == 0, return_indices=True)
    near = ids[near_i[0], near_i[1]]
    C.near, C.near_d = near, near_d

    def lookup(x, z, maxd=4.0):
        c, r = int((x - X0) / RC), int((z - Z0) / RC)
        if not (0 <= c < GW and 0 <= r < GH): return 0
        return ids[r, c] or (near[r, c] if near_d[r, c] * RC <= maxd else 0)

    fac_id = []
    for T in surf['facade']:
        tri = T[0]; n = np.cross(tri[1] - tri[0], tri[2] - tri[0]); n[1] = 0; l = np.linalg.norm(n)
        c = T.reshape(-1, 3).mean(0); i = 0
        if l > 1e-6:
            n /= l
            for s in (0.8, -0.8):
                cc, rr = int((c[0] - n[0] * s - X0) / RC), int((c[2] - n[2] * s - Z0) / RC)
                if 0 <= cc < GW and 0 <= rr < GH and ids[rr, cc]: i = ids[rr, cc]; break
        fac_id.append(i or lookup(c[0], c[2]))
    log('buildings (ids)', nb, '%.1fs' % (time.time() - t0))

    # ------------------------------------------------------------ gather surfaces per building
    roofs, facs = {}, {}
    for T, i in zip(surf['roof'], roof_id): roofs.setdefault(i, []).append(T)
    for T, i in zip(surf['facade'], fac_id):
        if i: facs.setdefault(i, []).append(T)
    m = C.meta
    at = lambda r_, c_: ids[np.clip(r_, 0, GH - 1), np.clip(c_, 0, GW - 1)]
    blds = []
    for i in sorted(set(roofs) | set(facs)):
        R = [clean_tris(T) for T in roofs.get(i, [])]; R = [T for T in R if len(T)]
        Fa = [clean_tris(T) for T in facs.get(i, [])]; Fa = [T for T in Fa if len(T)]
        allT = np.concatenate(R + Fa) if R or Fa else None
        if allT is None: continue
        c = allT.reshape(-1, 3).mean(0)
        ci, cj = int((c[0] - m['ox']) / m['cell']), int((c[2] - m['oz']) / m['cell'])
        if not (0 <= ci < m['nx'] and 0 <= cj < m['nz']): continue
        if not C.land[max(0, cj - 5):cj + 6, max(0, ci - 5):ci + 6].any(): continue
        # ground: the footprint's elevation; roof-only pieces take the nearest footprint's; else the lowest facade
        if i in foot_y: g = foot_y[i]
        else:
            cc, rr = int((c[0] - X0) / RC), int((c[2] - Z0) / RC)
            win = ids[max(0, rr - 40):rr + 41, max(0, cc - 40):cc + 41]
            fy = [foot_y[k] for k in np.unique(win) if k in foot_y]
            if fy: g = float(np.median(fy))
            elif Fa: g = float(np.concatenate(Fa)[..., 1].min())
            else: g = float(allT[..., 1].min())
        # roofs face up (the source mixes both windings); near-vertical roof pieces face away from the footprint
        R2 = []
        for T in R:
            n, _ = tri_normals(T); T = T.copy()
            flip = n[:, 1] < 0
            st = np.abs(n[:, 1]) < 0.3
            if st.any():
                cen = T[st].mean(1)
                pc = ((cen[:, 0] + n[st, 0] * 0.8 - X0) / RC).astype(int); pr = ((cen[:, 2] + n[st, 2] * 0.8 - Z0) / RC).astype(int)
                flip[np.nonzero(st)[0]] = at(pr, pc) == i
            T[flip] = T[flip][:, [0, 2, 1]]
            T[..., 1] -= g; R2.append(T)
        F2 = []
        for T in Fa:                                       # facades face away from their footprint (roofless buildings)
            n, _ = tri_normals(T); T = T.copy(); cen = T.mean(1)
            pc = ((cen[:, 0] + n[:, 0] * 0.8 - X0) / RC).astype(int); pr = ((cen[:, 2] + n[:, 2] * 0.8 - Z0) / RC).astype(int)
            qc = ((cen[:, 0] - n[:, 0] * 0.8 - X0) / RC).astype(int); qr = ((cen[:, 2] - n[:, 2] * 0.8 - Z0) / RC).astype(int)
            out_in, back_in = at(pr, pc) == i, at(qr, qc) == i
            bc = allT.mean((0, 1))
            away = (n[:, 0] * (cen[:, 0] - bc[0]) + n[:, 2] * (cen[:, 2] - bc[2])) < 0
            flip = np.where(out_in != back_in, out_in, away)
            T[flip] = T[flip][:, [0, 2, 1]]
            T[..., 1] -= g; F2.append(T)
        top = max([T[..., 1].max() for T in R2 + F2])
        if top < 2.0: continue
        roof_area = sum(tri_normals(T)[1].sum() for T in R2)
        blds.append({'id': int(i), 'roofs': R2, 'facades': F2, 'ground': float(g), 'keep_facades': roof_area < 1.0})
    log('buildings kept', len(blds), '(%d roofless: source facades kept)' % sum(b['keep_facades'] for b in blds))
    return blds, ids


def ground_texture(C, rng):
    """street / sidewalk / park ground texture from the DCP linework (0.5 m) + surface-class labels + overpasses"""
    t = time.time()
    GW, GH = C.GW, C.GH
    G = np.zeros((GH, GW, 3), np.uint8); G[:] = (156, 150, 140)                 # concrete sidewalk / plaza base
    def polys(*names):
        out = []
        for nm in names:
            for L in C.lines.get('Linework::' + nm, []):
                if len(L) < 3: continue
                q = C.px(C.tf(L)[None])[0]
                if q[:, 0].max() < 0 or q[:, 1].max() < 0 or q[:, 0].min() > GW or q[:, 1].min() > GH: continue
                out.append(np.round(q * 8).astype(np.int32))
        return out
    LAB = np.zeros((GH, GW), np.uint8)                                      # 0 sidewalk 1 open 2 parking 3 road 4 park
    def fill(pl, color, lab):
        for q in pl: cv2.fillPoly(G, [q], color, shift=3); cv2.fillPoly(LAB, [q], lab, shift=3)
    fill(polys('Open Space'), (166, 158, 146), 1)
    fill(polys('Parking Lots', 'Parking Lot'), (74, 75, 78), 2)
    fill(polys('Roadbed'), (54, 55, 58), 3)
    fill(polys('Parks', 'Park'), (84, 104, 62), 4)
    for q in polys('Edge of Pavement', 'Pavement Edge'): cv2.polylines(G, [q], False, (120, 117, 110), 2, cv2.LINE_AA, shift=3)
    BR = np.zeros((GH, GW), np.uint8)
    for q in polys('Bridge_Tunnel_Overpass'): cv2.fillPoly(BR, [q], 1, shift=3)
    # grain so large surfaces don't read as flat colour
    nz = rng.normal(0, 1, (GH // 4 + 1, GW // 4 + 1)); nz = cv2.resize(nz, (GW, GH), interpolation=cv2.INTER_CUBIC)
    fine = rng.normal(0, 1, (GH, GW))
    G = np.clip(G.astype(np.float32) * (1 + 0.05 * nz[..., None] + 0.035 * fine[..., None]), 0, 255).astype(np.uint8)
    log('linework ground %dx%d %.1fs' % (GW, GH, time.time() - t))
    return G, LAB, BR.astype(bool)


def scan_max_height(sampler, frame, shape):
    """highest point of any scan surface per cell (sees the walls of the scan's roofless 'hollow' towers)"""
    X0, Z0, RC_ = frame; GH, GW = shape
    T = sampler.P[sampler.fi].astype(np.float64)
    e1, e2 = T[:, 1] - T[:, 0], T[:, 2] - T[:, 0]
    Axz = 0.5 * np.abs(e1[:, 0] * e2[:, 2] - e1[:, 2] * e2[:, 0])
    L = np.maximum(np.linalg.norm(e1[:, [0, 2]], axis=1), np.linalg.norm(e2[:, [0, 2]], axis=1))
    n = np.clip(np.ceil(np.maximum(Axz / (RC_ * RC_) * 2, L / RC_ * 2)), 1, 20000).astype(np.int64)
    rng = np.random.default_rng(1)
    H = np.zeros((GH, GW), np.float32)
    idx = np.repeat(np.arange(len(T)), n)
    for s in range(0, len(idx), 4_000_000):
        ii = idx[s:s + 4_000_000]
        a = rng.random((len(ii), 1)); b = rng.random((len(ii), 1)); m = (a + b) > 1; a[m] = 1 - a[m]; b[m] = 1 - b[m]
        p = T[ii, 0] + e1[ii] * a + e2[ii] * b
        c = ((p[:, 0] - X0) / RC_).astype(int); r = ((p[:, 2] - Z0) / RC_).astype(int)
        ok = (c >= 0) & (c < GW) & (r >= 0) & (r < GH)
        np.maximum.at(H, (r[ok], c[ok]), p[ok, 1].astype(np.float32))
    return H


def grey_fill_holes(H, step=2.0):
    """fill basins enclosed by higher rims up to the rim (level-wise binary hole filling)"""
    out = H.copy()
    for L in np.arange(step, H.max() + step, step):
        m = H >= L
        if not m.any(): break
        f = nd.binary_fill_holes(m) & ~m
        out[f] = np.maximum(out[f], L)
    return out


def scan_only_buildings(C, blds, ids, sampler, Hs, Cs, LAB, BR):
    """Structures the scan shows but the 2014 DCP model lacks (newer towers, pier buildings): solid, flat-topped,
    non-vegetation, off the roadbed / overpasses, away from every NYC building. Each becomes terraced prisms
    (roof polygons per height tier; rebuild_walls adds the walls) in the NYC frame (the local registration
    offset is taken back out) and gets its footprint in `ids` so build_scan cuts the raw scan there."""
    import shapely
    from shapely.geometry import Polygon
    t0 = time.time()
    frame = (C.X0, C.Z0, RC); GH, GW = ids.shape
    Hm = scan_max_height(sampler, frame, ids.shape)
    # NYC buildings where the scan sees them (shifted by their registration)
    FP = np.zeros((GH, GW), np.uint8)
    for b in blds:
        o = b['reg']
        for R in b['roofs']:
            for tri in R:
                q = np.round(np.stack([(tri[:, 0] + o[0] - C.X0) / RC, (tri[:, 2] + o[1] - C.Z0) / RC], 1) * 8).astype(np.int32)
                cv2.fillPoly(FP, [q], 1, shift=3)
    FP = nd.binary_dilation(FP.astype(bool), iterations=4)
    g = Cs[..., 1]; veg = (g > Cs[..., 0] * 1.03) & (g > Cs[..., 2] * 0.97)
    vegf = cv2.blur(veg.astype(np.float32), (11, 11))
    gy, gx = np.gradient(nd.median_filter(Hs, 3)); steep = np.hypot(gx, gy) > 0.8        # > 1.6 m rise per metre
    li = np.clip(((C.X0 + (np.arange(GW) + 0.5) * RC - C.meta['ox']) / C.meta['cell']).astype(int), 0, C.meta['nx'] - 1)
    lj = np.clip(((C.Z0 + (np.arange(GH) + 0.5) * RC - C.meta['oz']) / C.meta['cell']).astype(int), 0, C.meta['nz'] - 1)
    land = C.land[lj][:, li] > 0
    Hf = grey_fill_holes(np.where(FP, 0, Hm))        # rims of NYC buildings don't count (courtyards stay open)
    road = nd.binary_dilation((LAB == 3) | BR, iterations=4)
    cand = (Hf > 9) & ~FP & ~road & land & (vegf < 0.3)
    cand = nd.binary_opening(cand, iterations=4)
    lab, nl = nd.label(cand)
    # average registration around each point (to go back from the scan frame to the NYC frame)
    cen = np.array([np.concatenate(b['roofs']).reshape(-1, 3).mean(0) for b in blds if b['roofs']])
    regs = np.array([b['reg'] for b in blds if b['roofs']])
    def local_reg(x, z):
        d = np.hypot(cen[:, 0] - x, cen[:, 2] - z); k = np.argsort(d)[:8]
        return np.median(regs[k], 0)
    new = []; nid = int(ids.max())
    for k, sl in enumerate(nd.find_objects(lab)):
        if sl is None: continue
        m = lab[sl] == k + 1; area = m.sum() * RC * RC
        if area < 150: continue
        hh = Hf[sl][m]
        if np.median(hh) < 12: continue
        # tree canopies (the colour test misses dark ones) are bumpy all over; roofs are mostly flat inside their edges
        inner = nd.binary_erosion(m, iterations=4) & (Hs[sl] > 0.6 * Hf[sl])
        if np.median(hh) < 30 and inner.sum() > 40 and steep[sl][inner].mean() > 0.45: continue
        cs, _ = cv2.findContours(m.astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        hull = cv2.convexHull(np.concatenate(cs)); ha = cv2.contourArea(hull) * RC * RC
        if area < 0.72 * ha: continue                      # solidity: tree clumps are ragged
        r0, c0 = sl[0].start, sl[1].start
        x_, z_ = C.X0 + (c0 + m.shape[1] / 2) * RC, C.Z0 + (r0 + m.shape[0] / 2) * RC
        reg = local_reg(x_, z_)
        # height tiers: modes of the (hole-filled) height, each tier = everything at least that tall
        Hc = nd.median_filter(np.where(m, Hf[sl], 0), 5)
        vals = Hc[m]
        hist, edges = np.histogram(vals, bins=np.arange(0, vals.max() + 4, 3.0))
        sm_ = np.convolve(hist, [1, 2, 1], 'same')
        levels = []
        for j in range(len(hist)):
            if sm_[j] >= max(sm_[max(j - 1, 0)], sm_[min(j + 1, len(hist) - 1)]) and hist[max(j - 1, 0):j + 2].sum() * RC * RC >= max(80, 0.08 * area):
                sel = (vals >= edges[max(j - 1, 0)]) & (vals < edges[min(j + 2, len(edges) - 1)])
                if sel.any(): levels.append(float(np.median(vals[sel])))
        levels = sorted(set(round(v, 1) for v in levels if v >= 6))
        if not levels: continue
        merged = [levels[0]]
        for v in levels[1:]:
            if v - merged[-1] < 4: merged[-1] = max(merged[-1], v)
            else: merged.append(v)
        roofs = []; foot = None
        for j, L in enumerate(merged):
            reg_m = nd.binary_opening(m & (Hc >= L - (2.0 if j else 3.0)), iterations=3)
            if reg_m.sum() * RC * RC < 60: continue
            cs, _ = cv2.findContours(reg_m.astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
            for cnt in cs:
                if cv2.contourArea(cnt) * RC * RC < 40: continue
                pts = cnt.reshape(-1, 2).astype(np.float64)
                P = Polygon(np.stack([C.X0 + (pts[:, 0] + c0 + 0.5) * RC - reg[0], C.Z0 + (pts[:, 1] + r0 + 0.5) * RC - reg[1]], 1))
                P = P.buffer(0)
                if P.is_empty or P.area < 40: continue
                rect = P.minimum_rotated_rectangle           # most towers are rectangles: don't keep raster jaggies
                P = rect if P.area >= 0.85 * rect.area else P.simplify(1.2, preserve_topology=True)
                if P.is_empty or P.area < 40: continue
                y = L - reg[2]
                for part in getattr(P, 'geoms', [P]):
                    tris = shapely.constrained_delaunay_triangles(part)
                    T = np.array([[(q[0], y, q[1]) for q in list(t.exterior.coords)[:3]] for t in tris.geoms])
                    if not len(T): continue
                    n = np.cross(T[:, 1] - T[:, 0], T[:, 2] - T[:, 0]); f = n[:, 1] < 0; T[f] = T[f][:, [0, 2, 1]]
                    roofs.append(T)
                if j == 0: foot = P if foot is None else foot.union(P)
        if not roofs or foot is None: continue
        nid += 1
        for poly in getattr(foot, 'geoms', [foot]):
            xy = np.array(poly.exterior.coords)
            q = np.round(np.stack([(xy[:, 0] - C.X0) / RC, (xy[:, 1] - C.Z0) / RC], 1) * 8).astype(np.int32)
            cv2.fillPoly(ids, [q], nid, shift=3)
        new.append({'id': nid, 'roofs': roofs, 'facades': [], 'ground': 0.0, 'keep_facades': False, 'reg': reg, 'scan_only': True})
        log('  scan-only building %d at (%.0f, %.0f): %.0f m2, tiers %s m' % (nid, x_ - reg[0], z_ - reg[1], area, [round(v - reg[2], 1) for v in merged]))
    # whatever tall, solid, non-vegetation scan structure is still left (thin towers, spires, fragments too small or
    # too odd to model) must not stand as raw scan: an id with no geometry, so build_scan cuts it
    rest = nd.binary_opening((Hf > 22) & ~FP & ~road & land & (vegf < 0.3), iterations=1) & (ids == 0)
    rest = nd.binary_dilation(rest, iterations=2) & (ids == 0)
    C.cut_id = None
    if rest.any():
        nid += 1; ids[rest] = nid; C.cut_id = nid
    log('scan-only buildings: %d, %.0f m2 of other raw scan structure cut (%.1fs)' % (len(new), rest.sum() * RC * RC, time.time() - t0))
    return new


def prepare(C):
    """geometry stages: DCP roofs per building, ground linework, registration against the scan, the scan's extra
    buildings, walls from roof edges -> (blds, ids, G, tex, sampler)"""
    X0, Z0 = C.X0, C.Z0
    blds, ids = load_buildings(C)
    G, LAB, BR = ground_texture(C, np.random.default_rng(11))
    tex = np.asarray(Image.open(BS.SRC_TEX).convert('RGB'))
    sampler = bake_nyc.ScanSampler(np.load(os.path.join(OUT, 'scan_flat.npz')), tex)
    Hs, Cs = bake_nyc.scan_topdown(sampler, (X0, Z0, RC), ids.shape)
    for b in blds: b['T'] = np.concatenate(b['roofs'] + b['facades'])
    for b, r in zip(blds, bake_nyc.register(blds, sampler, (X0, Z0, RC), ids.shape, Hs)): b['reg'] = r
    blds += scan_only_buildings(C, blds, ids, sampler, Hs, Cs, LAB, BR)
    rebuild_walls(blds)
    blds = [b for b in blds if len(b['T'])]
    for b in blds: b['reg'] = np.array(b['reg'], float)
    return blds, ids, G, tex, sampler


def main():
    t0 = time.time()
    C = Ctx()
    X0, Z0, GW, GH = C.X0, C.Z0, C.GW, C.GH
    rng = np.random.default_rng(7)
    blds, ids, G, tex, sampler = prepare(C)
    near_d, near_i = nd.distance_transform_edt(ids == 0, return_indices=True)
    near = ids[near_i[0], near_i[1]]
    nb = int(ids.max())

    # ------------------------------------------------------------ facade colours from the scan
    V, VT, F = BS.load_obj()
    P = V * BS.SCALE
    mn, mx = P.min(0), P.max(0)
    P[:, 0] -= (mn[0] + mx[0]) / 2; P[:, 2] -= (mn[2] + mx[2]) / 2
    TH, TW = tex.shape[:2]
    Ts = P[F[:, :, 0]]; Us = VT[F[:, :, 1]]
    nrm = np.cross(Ts[:, 1] - Ts[:, 0], Ts[:, 2] - Ts[:, 0]); area = np.linalg.norm(nrm, axis=1) * 0.5
    ny = np.abs(nrm[:, 1]) / np.maximum(area * 2, 1e-9)
    cen = Ts.mean(1); uvc = Us.mean(1)
    steep = (ny < 0.45) & (area > 0.05)
    col = tex[np.clip(((1 - uvc[:, 1]) * TH).astype(int), 0, TH - 1), np.clip((uvc[:, 0] * TW).astype(int), 0, TW - 1)].astype(np.float64)
    cc = ((cen[:, 0] - X0) / RC).astype(int); rr = ((cen[:, 2] - Z0) / RC).astype(int)
    ok = steep & (cc >= 0) & (cc < GW) & (rr >= 0) & (rr < GH)
    bid = np.zeros(len(F), np.int64)
    d3 = near_d[np.clip(rr, 0, GH - 1), np.clip(cc, 0, GW - 1)] * RC
    bid[ok & (d3 <= 3.0)] = near[rr[ok & (d3 <= 3.0)], cc[ok & (d3 <= 3.0)]]
    sel = np.nonzero(bid)[0]
    wsum = np.bincount(bid[sel], weights=area[sel], minlength=nb + 1)
    csum = np.stack([np.bincount(bid[sel], weights=area[sel] * col[sel, k], minlength=nb + 1) for k in range(3)], 1)
    log('scan colour samples', len(sel))

    FA = {'GLASS': 0, 'STONE': 1, 'BRICK': 2, 'INDUSTRIAL': 3, 'BROWNSTONE': 4, 'OFFICE': 5}
    # real Lower Manhattan facade materials; the scan colour (white-balanced: the capture has a strong sky-blue
    # cast) picks the nearest family and adds a little per-building variation
    PAL = [('limestone', (198, 184, 160), 'STONE'), ('sandstone', (182, 164, 136), 'STONE'), ('granite', (152, 150, 146), 'STONE'),
           ('darkgranite', (112, 110, 108), 'OFFICE'), ('whiteconc', (214, 210, 202), 'OFFICE'), ('redbrick', (146, 76, 60), 'BRICK'),
           ('brownbrick', (116, 84, 66), 'BRICK'), ('tanbrick', (170, 128, 96), 'BRICK'), ('darkglass', (58, 70, 84), 'GLASS'),
           ('blueglass', (84, 112, 138), 'GLASS'), ('greenglass', (82, 112, 108), 'GLASS'), ('black', (46, 47, 52), 'OFFICE')]
    have = [b for b in blds if wsum[b['id']] > 1]
    allc = np.array([csum[b['id']] / wsum[b['id']] for b in have]) if have else np.ones((1, 3)) * 140
    gain = np.array([150, 145, 138.0]) / np.maximum(allc.mean(0), 1)
    log('white balance gain', np.round(gain, 3))
    for b in blds:
        h = float(b['T'][..., 1].max())
        c = csum[b['id']] / wsum[b['id']] * gain if wsum[b['id']] > 1 else np.array([170, 160, 145.0])
        lum = c.mean(); c = np.clip((c - lum) * 1.6 + lum * 1.12, 20, 240)
        w = np.array([1.0, 1.3, 0.8])
        cand = [(np.sum(w * (np.array(pc) - c) ** 2) + (4000 if st_ == 'GLASS' and h < 30 else 0), nm, pc, st_) for nm, pc, st_ in PAL]
        _, nm, pc, st = min(cand)
        if st == 'BRICK' and h < 16: st = 'BROWNSTONE'
        if st == 'STONE' and h > 110: st = 'OFFICE'
        c = np.clip(np.array(pc) * 0.7 + c * 0.3 + rng.normal(0, 5, 3), 15, 245)
        r, g, bl = c
        b['style'] = FA[st]
        b['color'] = int(r) << 16 | int(g) << 8 | int(bl)
        tr = np.clip(c * (0.7 if st in ('GLASS', 'OFFICE') else 1.18), 0, 255)
        b['trim'] = int(tr[0]) << 16 | int(tr[1]) << 8 | int(tr[2])
        b['floorH'] = round(float(rng.uniform(3.2, 3.5) if st in ('BRICK', 'BROWNSTONE') else rng.uniform(3.7, 4.3)), 2)
        b['ww'] = 1.6 if st == 'GLASS' else 2.4 if st == 'BROWNSTONE' else 3.0
        b['seed'] = int(rng.integers(1, 250))
        b['h'] = round(h, 2)

    # ------------------------------------------------------------ colliders: per building, in its own orientation
    t = time.time()
    boxes = []
    def footprint_test(bid):
        def f(wx, wz):
            c = np.floor((wx - X0) / RC).astype(int); r = np.floor((wz - Z0) / RC).astype(int)
            ok = (c >= 0) & (c < GW) & (r >= 0) & (r < GH)
            return ok & (ids[np.clip(r, 0, GH - 1), np.clip(c, 0, GW - 1)] == bid)
        return f
    for b in blds: boxes += [bx + (b['id'],) for bx in building_colliders(b['T'], rng, inside=footprint_test(b['id']))]
    boxes = np.array(boxes, np.float32)
    log('colliders', len(boxes), '%.1fs' % (time.time() - t))

    # ------------------------------------------------------------ bake the scan's real colour onto buildings
    t = time.time()
    atlas, texel = bake_nyc.bake_buildings(blds, sampler, ids=ids, frame=(X0, Z0, RC))
    Image.fromarray(atlas).save(os.path.join(OUT, 'nyc_atlas.webp'), 'WEBP', quality=82, method=4)
    # (bake_nyc.bake_ground can drape the scan's own street imagery here, but in the canyons it is mostly
    #  shadowed / missing and reads blotchy, so the clean linework ground is used as is)
    Image.fromarray(G).save(os.path.join(OUT, 'nyc_ground.jpg'), 'JPEG', quality=85)
    log('bake done %.1fs' % (time.time() - t))

    # ------------------------------------------------------------ pack
    order = sorted(range(len(blds)), key=lambda k: (int((blds[k]['T'][..., 2].mean() - Z0) // TILE), int((blds[k]['T'][..., 0].mean() - X0) // TILE)))
    parts, off, B = [], 0, []
    for k in order:
        b = blds[k]
        arr = b['T'].astype(np.float32).tobytes() + b['UV'].astype(np.float32).tobytes()
        B.append({'o': off, 'uo': off + b['T'].size * 4, 'n': len(b['T']), 'st': b['style'], 'c': b['color'], 't': b['trim'], 'fh': b['floorH'], 'ww': b['ww'], 'sd': b['seed'],
                  'h': b['h'], 'id': b['id'], 'x': round(float(b['T'][..., 0].mean()), 1), 'z': round(float(b['T'][..., 2].mean()), 1)})
        parts.append(arr); off += len(arr)
    box_off = off; parts.append(boxes.tobytes()); off += boxes.nbytes
    with open(os.path.join(OUT, 'nyc.bin'), 'wb') as f:
        for p in parts: f.write(p)
    json.dump({'v': 2, 'src': 'NYC DCP 3D Model 2014 (MN01, MN03)', 'buildings': B, 'texel': round(texel, 3),
               'ground': {'x0': X0, 'z0': Z0, 'w': GW * RC, 'h': GH * RC}, 'boxes': {'o': box_off, 'n': int(len(boxes)), 'stride': 7}, 'bytes': off},
              open(os.path.join(OUT, 'nyc.json'), 'w'), separators=(',', ':'))
    np.savez_compressed(os.path.join(OUT, 'nyc_mask.npz'), ids=ids, x0=X0, z0=Z0, rc=RC,
                        kept=np.array([b['id'] for b in blds] + ([C.cut_id] if getattr(C, 'cut_id', None) else []), np.int32))
    log('nyc.bin %.2f MB, %d buildings, %d colliders, total %.1fs' % (off / 1048576, len(B), len(boxes), time.time() - t0))


if __name__ == '__main__':
    main()
