'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const harness=process.env.TL_HARNESS||path.join(process.env.LOCALAPPDATA,'Temp/claude/c--Users-PRIYANSHU-Pictures-spooderman/3daa858f-ae71-47ed-a4cc-f3ea76aee61c/scratchpad/harness');
global.THREE=require(path.join(harness,'node_modules/three/build/three.cjs'));
for(const f of ['00_core.js','02_collision.js','04_physics.js','04b_contact.js','03o_construction_cranes.js'])vm.runInThisContext(fs.readFileSync(path.join(__dirname,'../src',f),'utf8'),{filename:f});
TL.V.init();const sharedGeometry=new THREE.BoxGeometry(),sharedMaterial=new THREE.MeshBasicMaterial();
TL.Assets={mesh:()=>new THREE.Mesh(sharedGeometry,sharedMaterial),pickLod:()=>'hi',shared:()=>sharedMaterial};
let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}
function setup(baseY=24){const world={world:new TL.CollisionWorld(),scene:new THREE.Scene(),quality:'medium'};world.world.groundFn=()=>0;world.world.addStatic(0,baseY/2,0,8,baseY/2,8,0,{kind:'building'});world.constructionState={sites:[{id:'construction-0',name:'Test Site',yaw:0,crane:{x:0,z:0,baseY,topY:baseY+63,yaw:0}}]};return world;}
test('mast is based on real elevated support and meshes match initial dynamic collider transforms',()=>{const w=setup(),c=TL.ConstructionCranes.build(w).cranes[0];assert(c);assert.equal(c.mast.position.y,24);assert.equal(c.mastCol.cy-c.mastCol.hy,24);assert.equal(c.jib.position.y,87);assert.equal(c.hook.position.y+.7,c.hookCol.cy);for(const p of c.parts){const q=TL.ConstructionCranes.point(c,...p.local.slice(0,3));assert(Math.hypot(q.x-p.col.cx,q.y-p.col.cy,q.z-p.col.cz)<1e-8);assert.equal(p.col.vx,0);}});
test('bounded slew avoids nearby facades throughout a complete oscillation',()=>{const w=setup();const block=w.world.addStatic(39,95,-22,10,20,8,0,{kind:'building'});const c=TL.ConstructionCranes.build(w).cranes[0];assert(c);let lo=Infinity,hi=-Infinity;for(let i=0;i<4000;i++){TL.ConstructionCranes.update(w,1/60);lo=Math.min(lo,c.yaw);hi=Math.max(hi,c.yaw);for(const p of c.parts)assert(!TL.ConstructionCranes.overlap(p.col,block));assert(!TL.ConstructionCranes.overlap(c.hookCol,block));}assert(hi-lo>.2);assert(lo>=c.midYaw-c.amplitude-1e-8&&hi<=c.midYaw+c.amplitude+1e-8);});
test('moving anchor follows local attachment with correct tangential velocity',()=>{const w=setup(),c=TL.ConstructionCranes.build(w).cranes[0],col=c.parts[0].col,r=new TL.Rope(),p=col.toWorld(20,col.hy,0,new THREE.Vector3());r.attachTo({x:p.x,y:p.y,z:p.z,col},w.world);r.active=r.attached=true;let maxError=0;for(let i=0;i<180;i++){const previous=r.anchor.clone();TL.ConstructionCranes.update(w,1/120);r.updateAnchor(1/120);const actual=r.anchor.clone().sub(previous).multiplyScalar(120);maxError=Math.max(maxError,actual.distanceTo(r.anchorVel));const expected=col.toWorld(20,col.hy,0,new THREE.Vector3());assert(r.anchor.distanceTo(expected)<1e-8);}assert(maxError<.006,'Point velocity consistent with rotating mesh '+maxError);assert(r.anchorVel.length()>.5);});
for(const hz of [30,60,120])test('swing stays finite, constrained and preserves release momentum on moving crane at '+hz+'Hz',()=>{const w=setup(),c=TL.ConstructionCranes.build(w).cranes[0],h=new TL.HeroController(w.world,TL.HERO_STATS.PULSE),col=c.parts[0].col,anchor=col.toWorld(14,-col.hy,0,new THREE.Vector3()),r=h.tether.main;h.teleport(anchor.x,anchor.y-17,anchor.z);h.vel.set(0,0,14);r.attachTo({x:anchor.x,y:anchor.y,z:anchor.z,col},w.world);r.active=r.attached=true;r.L=r.targetL=17;r.maxL=100;h.fsm.set(TL.TS.SWING);const it={move:new THREE.Vector3(),moveLocal:{x:0,y:0},camFwd:new THREE.Vector3(0,0,1),camRight:new THREE.Vector3(1,0,0),swing:true};let stretch=0;for(let i=0;i<hz*2;i++){TL.ConstructionCranes.update(w,1/hz);h.step(1/hz,it);assert(TL.finite3(h.pos)&&TL.finite3(h.vel));stretch=Math.max(stretch,h.pos.distanceTo(r.anchor)/r.L);}assert(r.attached);assert(stretch<1.06);const vel=h.vel.clone();h.releaseSwing(false,it);assert(h.vel.equals(vel));assert.equal(h.nanResets,0);});
test('hook reacts to web impulses but stays inside checked cable envelope',()=>{const w=setup(),c=TL.ConstructionCranes.build(w).cranes[0];c.hookCol.owner.applyImpulse(50,10,-30);for(let i=0;i<600;i++){TL.ConstructionCranes.update(w,1/60);const t=TL.ConstructionCranes.point(c,40,2.4,0);assert(c.hookPos.distanceTo(t)<=c.drop+.001);assert(Math.hypot(c.hookPos.x-t.x,c.hookPos.z-t.z)<=1.201);assert(TL.finite3(c.hookPos));assert.equal(c.hookCol.cx,c.hook.position.x);}});
test('blocked mast is skipped rather than placing a moving crane inside a facade',()=>{const w=setup();w.world.addStatic(0,65,0,24,20,24,0,{kind:'building'});const s=TL.ConstructionCranes.build(w);assert.equal(s.cranes.length,0);assert.deepEqual(s.skipped,['construction-0']);assert.equal(w.world.dynamics.length,0);});
test('full-footprint unfinished floors move crane to a supported perimeter footing',()=>{const w=setup(),site=w.constructionState.sites[0];Object.assign(site,{center:new THREE.Vector3(),baseY:24,footprint:{bounds:{minX:-40,minZ:-30,maxX:40,maxZ:30}}});const floor=w.world.addStatic(0,45,0,40,20,30,0,{kind:'building'});const c=TL.ConstructionCranes.build(w).cranes[0];assert(c);assert(Math.abs(c.x)>40||Math.abs(c.z)>30);assert.equal(c.baseY,0);assert(!TL.ConstructionCranes.overlap(c.mastCol,floor));});
test('metadata support is snapped to the real roof and zero elapsed time leaves paused cranes still',()=>{const w=setup();w.constructionState.sites[0].baseY=24;w.constructionState.sites[0].crane.baseY=12;const c=TL.ConstructionCranes.build(w).cranes[0];assert(c);assert.equal(c.baseY,24);const yaw=c.yaw,p=c.hookPos.clone();TL.ConstructionCranes.update(w,0);assert.equal(c.yaw,yaw);assert(c.hookPos.equals(p));});
test('dynamic broadphase sees current positions and disposal leaves shared asset resources alive',()=>{const w=setup(),count=w.world.count,c=TL.ConstructionCranes.build(w).cranes[0];for(let i=0;i<200;i++)TL.ConstructionCranes.update(w,1/60);const col=c.parts[0].col,list=[];w.world.query(col.cx-.1,col.cz-.1,col.cx+.1,col.cz+.1,list);assert(list.includes(col));let disposed=false;sharedGeometry.addEventListener('dispose',()=>disposed=true);TL.ConstructionCranes.dispose(w);assert.equal(w.world.count,count);assert.equal(w.world.dynamics.length,0);assert.equal(w.scene.children.length,0);assert(!disposed);assert(!w.constructionCraneState);});
test('low, medium and high presets load the actual shipped procedural crane assets',()=>{
 vm.runInThisContext(fs.readFileSync(path.join(__dirname,'../src/01_assets.js'),'utf8'));TL.Assets.man=require('../build/assets.json');const data=fs.readFileSync(path.join(__dirname,'../build/assets.bin'));TL.Assets.bin=data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength);
 for(const quality of ['low','medium','high']){const w=setup();w.quality=quality;const c=TL.ConstructionCranes.build(w).cranes[0];assert(c);for(const m of [c.mast,c.jib,c.hook])assert(m.geometry.attributes.position.count>50);TL.ConstructionCranes.update(w,1/60);assert.equal(c.jib.rotation.y,c.parts[0].col.yaw);TL.ConstructionCranes.dispose(w);}
});
console.log(passed+' moving construction crane checks passed');
