'use strict';
const {launch}=require('./graphics_bench/lib'),fs=require('fs'),path=require('path');
(async()=>{const {browser,page}=await launch({headless:true,w:1400,h:950});try{await page.goto('about:blank');await page.setContent('<script src="https://cdn.jsdelivr.net/npm/three@0.149.0/build/three.min.js"></script>');await page.waitForFunction(()=>window.THREE?.Scene);await page.evaluate(data=>{
 const scene=new THREE.Scene();scene.background=new THREE.Color('#d6dce0');const camera=new THREE.PerspectiveCamera(37,1400/950,.1,100);camera.position.set(13,12,17);camera.lookAt(4,.7,2.7);const r=new THREE.WebGLRenderer({antialias:true});r.setSize(1400,950);r.setPixelRatio(1);r.outputEncoding=THREE.sRGBEncoding;r.toneMapping=THREE.ACESFilmicToneMapping;r.toneMappingExposure=.8;r.shadowMap.enabled=true;document.body.style.margin=0;document.body.appendChild(r.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x5b6570,1.2));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(-4,10,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-15,right:15,top:15,bottom:-15});scene.add(sun);
 const palette={concrete:0xb4ab8c,steel:0x333f48,wood:0x63432a,timber:0xb58c50,rust:0x77412b,orange:0xd89524};const mats={};for(const[k,c]of Object.entries(palette))mats[k]=new THREE.MeshStandardMaterial({color:c,roughness:.85,metalness:k==='steel'?.45:0});
 for(const p of data.parts){let geo,mesh;if(p.shape==='box'){geo=new THREE.BoxGeometry(p.hx*2,p.hy*2,p.hz*2);mesh=new THREE.Mesh(geo,mats[p.mat]);mesh.position.set(p.x,p.y,p.z);}else if(p.shape==='footprint'){geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(p.positions,3));geo.computeVertexNormals();mesh=new THREE.Mesh(geo,mats[p.mat]);}else{const a=new THREE.Vector3(...p.a),b=new THREE.Vector3(...p.b),d=b.clone().sub(a);geo=new THREE.CylinderGeometry(p.r,p.r,d.length(),8);mesh=new THREE.Mesh(geo,mats[p.mat]);mesh.position.copy(a).add(b).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());}mesh.castShadow=mesh.receiveShadow=true;scene.add(mesh);}
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(30,25),new THREE.MeshStandardMaterial({color:0xbfc6ca,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.006;floor.receiveShadow=true;scene.add(floor);r.render(scene,camera);
 },JSON.parse(fs.readFileSync(path.join(__dirname,'../evidence/construction/detail_preview.json'),'utf8')));await page.screenshot({path:path.join(__dirname,'../evidence/construction/detail_preview.png')});console.log('Saved exact detailed prop geometry preview');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

