'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const harness=process.env.TL_HARNESS||path.join(process.env.LOCALAPPDATA,'Temp/claude/c--Users-PRIYANSHU-Pictures-spooderman/3daa858f-ae71-47ed-a4cc-f3ea76aee61c/scratchpad/harness');global.THREE=require(path.join(harness,'node_modules/three/build/three.cjs'));
for(const f of ['00_core.js','02_collision.js','04_physics.js','04b_contact.js','04c_reference.js'])vm.runInThisContext(fs.readFileSync(path.join(__dirname,'../src',f),'utf8'),{filename:f});TL.V.init();
const results=[];
for(const name of ['PULSE','WEAVER'])for(const speed of [15,35,60])for(const sign of [-1,1])for(const dt of [1/30,1/120])for(const offAxis of [false,true]){
 const w=new TL.CollisionWorld();w.groundFn=()=>0;const yaw=.63,c=Math.cos(yaw),s=Math.sin(yaw),point=(x,y,z)=>new THREE.Vector3(x*c+z*s,100+y,-x*s+z*c),axis=new THREE.Vector3(s,0,c).multiplyScalar(sign),right=new THREE.Vector3(c,0,-s);
 const cols=[];for(const [x,y,hx,hy]of [[-1.85,0,.15,1.85],[1.85,0,.15,1.85],[0,-1.85,1.85,.15],[0,1.85,1.85,.15]]){const p=point(x,y,0);cols.push(w.addStatic(p.x,p.y,p.z,hx,hy,3,yaw,{kind:'building'}));}
 const gate={type:'pipe',center:point(0,-.12,0),axis:new THREE.Vector3(s,0,c),length:6,anchorsBySide:{}};for(const [key,z]of [['positive',-3],['negative',3]])gate.anchorsBySide[key]=[-1,1].map((side,i)=>{const p=point(side*1.85,0,z);return{x:p.x,y:p.y,z:p.z,col:cols[i]};});w.referenceGates=[gate];
 const h=new TL.HeroController(w,TL.HERO_STATS[name]);h.teleport(...gate.center.clone().addScaledVector(axis,-13).addScaledVector(right,offAxis?.85:0).toArray());h.fsm.set(TL.TS.SWING);h.grounded=false;
 h.vel.copy(axis).multiplyScalar(offAxis?.78:1).addScaledVector(right,offAxis?-.28:0);h.vel.y=offAxis?.48:0;h.vel.normalize().multiplyScalar(speed);
 const old=w.addStatic(h.pos.x,130,h.pos.z,2,.5,2,0,{kind:'building'}),rope=h.tether.main;rope.kind='swing';rope.active=rope.attached=true;rope.attachTo({x:old.cx,y:129.5,z:old.cz,col:old});rope.L=rope.targetL=30;
 const it={move:axis.clone(),moveLocal:{x:0,y:1},camFwd:gate.center.clone().sub(h.pos).normalize(),camRight:right.clone().negate(),swing:true,tether:true};
 const start=h.pos.clone(),initial=h.vel.clone();TL.ReferenceTraversal.tick(h,0,it);assert.equal(h.reference.action?.kind,'pass_through');assert(h.vel.equals(initial)&&h.pos.equals(start));const pathLength=h.reference.action.path.total,trace=[];let travelled=0,time=0,exited=false;
 for(let i=0;i<500;i++){const prev=h.pos.clone();h.step(dt,it);time+=dt;travelled+=h.pos.distanceTo(prev);const along=h.pos.clone().sub(gate.center).dot(axis);trace.push({t:time,speed:h.vel.length(),along,y:h.pos.y,stage:along< -3?'approach':along<=3?'bore':'exit'});assert(h.pos.distanceTo(prev)<=speed*dt*1.015,'no teleport/overshoot');assert(h.vel.length()>=speed*.99,'full incoming momentum retained, including off-axis component');assert(h.vel.length()<=speed*1.012,'no hidden boost');if(h.reference.action?.kind!=='pass_through'){assert(along>4,'pass exits entire bore');exited=true;break;}}
 assert(exited);assert(time<pathLength/speed+dt*2.1,'arrival time reflects full incoming speed');assert(travelled>pathLength-.6);const row={name,speed,sign,dt,offAxis,pathLength,travelled,time,minSpeed:Math.min(...trace.map(p=>p.speed)),maxSpeed:Math.max(...trace.map(p=>p.speed)),trace};results.push(row);console.log('PASS '+name+' '+speed+'m/s '+(offAxis?'swing arc':'aligned')+' side'+sign+' @'+1/dt+' min='+row.minSpeed.toFixed(3)+' duration='+time.toFixed(3));
}
fs.mkdirSync(path.join(__dirname,'../evidence/construction'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../evidence/construction/zip_speed_trace.json'),JSON.stringify(results,null,2));console.log(results.length+' full-speed curved swing-to-pipe sequences passed');
