'use strict';
require('./hand_swing_test.js');const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');for(const f of ['04c_reference.js','06e_reference_anim.js'])vm.runInThisContext(fs.readFileSync(path.join(__dirname,'../src',f),'utf8'),{filename:f});
for(const name of ['WEAVER','PULSE'])for(const mechanical of name==='WEAVER'?[false,true]:[false])for(const sign of [-1,1]){
 const w=new TL.CollisionWorld();w.groundFn=()=>0;const h=new TL.HeroController(w,TL.HERO_STATS[name]);h.teleport(0,100,-6*sign);h.fsm.set(TL.TS.AIR);h.vel.set(0,0,35*sign);h.facing=sign>0?0:Math.PI;h.tuck=1;h.shape=TL.BodyShapes.tuck;
 const mat=TL.Assets.material(),scene=new THREE.Scene(),sk=TL.Assets.skinned(name,'mid',mat),an=new TL.HeroAnimator(sk,name,scene,mat,'high');an.arms?.setRetracted(!mechanical,true);
 const axis=new THREE.Vector3(0,0,sign),a=TL.ReferenceTraversal.begin(h,'pass_through',3);Object.assign(a,{entry:new THREE.Vector3(0,100,-4*sign),exit:new THREE.Vector3(0,100,8*sign),axis,approachDistance:8,gate:{type:'pipe',center:new THREE.Vector3(0,100,0),length:6}});a.t=.3;
 for(let i=0;i<60;i++)an.update(1/120,h,h.pos,{fwd:axis});let previous=an.rootQ.clone(),turn=0,samples=[];
 for(let i=0;i<=96;i++){h.pos.z=(-4+i/12)*sign;const physical=h.pos.clone(),velocity=h.vel.clone();an.update(1/120,h,h.pos,{fwd:axis});const d=previous.clone().invert().multiply(an.rootQ);if(d.w<0)d.set(-d.x,-d.y,-d.z,-d.w);const n=Math.hypot(d.x,d.y,d.z);if(n>1e-8)turn+=2*Math.atan2(n,d.w)*d.y/n;previous.copy(an.rootQ);samples.push(an.passageSpin);assert(h.pos.equals(physical)&&h.vel.equals(velocity));assert(Object.values(an.rig.cur).every(TL.finite3));if(an.arms){assert.equal(an.arms.retracted,!mechanical);assert(an.arms.arms.every(arm=>TL.finite3(arm.tip)));}}
 assert(turn>6.1&&turn<6.5,'actual rendered root completes full360 corkscrew, not just pose metadata');assert(samples.some(v=>v>Math.PI*.9&&v<Math.PI*1.1),'visibly inverted midpoint');assert(samples.some(v=>v>Math.PI*1.5),'threequarter turn survives shortest-path smoothing');console.log('PASS '+name+' mechanical='+mechanical+' side='+sign+' actual root turn '+(turn*180/Math.PI).toFixed(2)+'degrees');
}
