"""Regenerates BASELINE.md: sha256 of every pre-existing file the life branch modifies, as found in MAIN (the worktree's origin) now.
usage: python tools/life_baseline.py [main folder]"""
import hashlib, os, subprocess, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
MAIN = sys.argv[1] if len(sys.argv) > 1 else os.path.abspath(os.path.join(ROOT, '..', 'spooderman'))


def h(p): return hashlib.sha256(open(p, 'rb').read()).hexdigest()


def git_h(path):
    blob = subprocess.run(['git', '-C', ROOT, 'show', 'a0bd459:' + path], capture_output=True).stdout
    return hashlib.sha256(blob).hexdigest()


MODIFIED = ['src/10_crowd.js', 'src/03c_trees.js', 'tools/build.js', 'tools/hd/trees_gen.py']
WATCH = ['src/10b_citylife.js', 'src/06_anim.js', 'src/16_game.js', 'src/11_traffic.js', 'src/03b_scan.js']
rows = []
for f in MODIFIED:
    rows.append((f, h(os.path.join(MAIN, f)), git_h(f), 'modified'))
ex = os.path.join(MAIN, 'build', 'extra')
for f in sorted(os.listdir(ex)):
    if f.startswith('trees_'): rows.append(('build/extra/' + f, h(os.path.join(ex, f)), '-', 'regenerated by tools/hd/trees_gen.py (variants)' if f.startswith('trees_models') or f.startswith('trees_leaf') or f.startswith('trees_bark') else 'unchanged'))
for f in WATCH:
    rows.append((f, h(os.path.join(MAIN, f)), git_h(f), 'not modified (watch for drift)'))
out = ['# BASELINE - spooderman_life', '',
       'Worktree made 2026-10-02 from the then-current main folder, git baseline commit `a0bd459` (line endings preserved, `core.autocrlf=false`;',
       'big data dirs build/, source/, textures/ are git-ignored but were copied).', '',
       'sha256 of the files this branch modifies / regenerates, taken from MAIN **when this file was generated**, next to the hash of the copy the branch started from:', '',
       '| file | sha256 in main now | sha256 at baseline commit | status |', '|---|---|---|---|']
for f, a, b, st in rows:
    out.append('| %s | `%s` | %s | %s |' % (f, a[:16], ('`%s`' % b[:16]) if b != '-' else '-', st + ('' if b == '-' or a == b else '  **MAIN HAS CHANGED - merge by hand**')))
out += ['', 'A row marked MAIN HAS CHANGED means main moved on after the worktree was cut: apply the branch diff (`git diff a0bd459 -- <file>`) instead of copying the file.', '',
        'New files (no baseline): src/10c_crowdnav.js, 10d_crowdlife.js, 10e_npcposes.js, 03l_lifeprops.js, 03m_waterfront.js; tools/scan/crowd_nav.py, waterfront.py;',
        'tools/hd/life_export.py, life_props.py, life_water.py; tests/crowd_life_test.js, waterfront_test.js, tests/life/*.']
open(os.path.join(ROOT, 'BASELINE.md'), 'w', encoding='utf8').write('\n'.join(out) + '\n')
print('\n'.join(out))
